/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MayorRouteImport } from './routes/mayor'
import { Route as PedidoRouteImport } from './routes/pedido'
import { Route as TestDiagnosticoRouteImport } from './routes/test-diagnostico'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminCajaRouteImport } from './routes/_authenticated/admin.caja'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminConfiguracionRouteImport } from './routes/_authenticated/admin.configuracion'
import { Route as AuthenticatedAdminInventarioRouteImport } from './routes/_authenticated/admin.inventario'
import { Route as AuthenticatedAdminKardexRouteImport } from './routes/_authenticated/admin.kardex'
import { Route as AuthenticatedAdminPagosRouteImport } from './routes/_authenticated/admin.pagos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminPosRouteImport } from './routes/_authenticated/admin.pos'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin.productos'
import { Route as AuthenticatedAdminReportesRouteImport } from './routes/_authenticated/admin.reportes'
import { Route as AuthenticatedAdminVentasRouteImport } from './routes/_authenticated/admin.ventas'
import { Route as ApiPublicProductImageSplatRouteImport } from './routes/api/public/product-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MayorRoute = MayorRouteImport.update({
  id: '/mayor',
  path: '/mayor',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRoute = PedidoRouteImport.update({
  id: '/pedido',
  path: '/pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDiagnosticoRoute = TestDiagnosticoRouteImport.update({
  id: '/test-diagnostico',
  path: '/test-diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCajaRoute = AuthenticatedAdminCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracionRoute =
  AuthenticatedAdminConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventarioRoute =
  AuthenticatedAdminInventarioRouteImport.update({
    id: '/inventario',
    path: '/inventario',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKardexRoute =
  AuthenticatedAdminKardexRouteImport.update({
    id: '/kardex',
    path: '/kardex',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagosRoute = AuthenticatedAdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPosRoute = AuthenticatedAdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportesRoute =
  AuthenticatedAdminReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVentasRoute =
  AuthenticatedAdminVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicProductImageSplatRoute =
  ApiPublicProductImageSplatRouteImport.update({
    id: '/api/public/product-image/$',
    path: '/api/public/product-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/mayor': typeof MayorRoute
  '/pedido': typeof PedidoRoute
  '/test-diagnostico': typeof TestDiagnosticoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/caja': typeof AuthenticatedAdminCajaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/admin/kardex': typeof AuthenticatedAdminKardexRoute
  '/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/mayor': typeof MayorRoute
  '/pedido': typeof PedidoRoute
  '/test-diagnostico': typeof TestDiagnosticoRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/caja': typeof AuthenticatedAdminCajaRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/admin/kardex': typeof AuthenticatedAdminKardexRoute
  '/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/pos': typeof AuthenticatedAdminPosRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/mayor': typeof MayorRoute
  '/pedido': typeof PedidoRoute
  '/test-diagnostico': typeof TestDiagnosticoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/_authenticated/admin/caja': typeof AuthenticatedAdminCajaRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/configuracion': typeof AuthenticatedAdminConfiguracionRoute
  '/_authenticated/admin/inventario': typeof AuthenticatedAdminInventarioRoute
  '/_authenticated/admin/kardex': typeof AuthenticatedAdminKardexRoute
  '/_authenticated/admin/pagos': typeof AuthenticatedAdminPagosRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/pos': typeof AuthenticatedAdminPosRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/reportes': typeof AuthenticatedAdminReportesRoute
  '/_authenticated/admin/ventas': typeof AuthenticatedAdminVentasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/product-image/$': typeof ApiPublicProductImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/categorias'
    | '/checkout'
    | '/mayor'
    | '/pedido'
    | '/test-diagnostico'
    | '/admin'
    | '/auth/callback'
    | '/producto/$slug'
    | '/admin/caja'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/pagos'
    | '/admin/pedidos'
    | '/admin/pos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/ventas'
    | '/admin/'
    | '/api/public/product-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/categorias'
    | '/checkout'
    | '/mayor'
    | '/pedido'
    | '/test-diagnostico'
    | '/auth/callback'
    | '/producto/$slug'
    | '/admin/caja'
    | '/admin/categorias'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/pagos'
    | '/admin/pedidos'
    | '/admin/pos'
    | '/admin/productos'
    | '/admin/reportes'
    | '/admin/ventas'
    | '/admin'
    | '/api/public/product-image/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrito'
    | '/catalogo'
    | '/categorias'
    | '/checkout'
    | '/mayor'
    | '/pedido'
    | '/test-diagnostico'
    | '/_authenticated/admin'
    | '/auth/callback'
    | '/producto/$slug'
    | '/_authenticated/admin/caja'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/configuracion'
    | '/_authenticated/admin/inventario'
    | '/_authenticated/admin/kardex'
    | '/_authenticated/admin/pagos'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/pos'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/reportes'
    | '/_authenticated/admin/ventas'
    | '/_authenticated/admin/'
    | '/api/public/product-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CatalogoRoute: typeof CatalogoRoute
  CategoriasRoute: typeof CategoriasRoute
  CheckoutRoute: typeof CheckoutRoute
  MayorRoute: typeof MayorRoute
  PedidoRoute: typeof PedidoRoute
  TestDiagnosticoRoute: typeof TestDiagnosticoRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
  ApiPublicProductImageSplatRoute: typeof ApiPublicProductImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mayor': {
      id: '/mayor'
      path: '/mayor'
      fullPath: '/mayor'
      preLoaderRoute: typeof MayorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido': {
      id: '/pedido'
      path: '/pedido'
      fullPath: '/pedido'
      preLoaderRoute: typeof PedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-diagnostico': {
      id: '/test-diagnostico'
      path: '/test-diagnostico'
      fullPath: '/test-diagnostico'
      preLoaderRoute: typeof TestDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/caja': {
      id: '/_authenticated/admin/caja'
      path: '/caja'
      fullPath: '/admin/caja'
      preLoaderRoute: typeof AuthenticatedAdminCajaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracion': {
      id: '/_authenticated/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventario': {
      id: '/_authenticated/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AuthenticatedAdminInventarioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kardex': {
      id: '/_authenticated/admin/kardex'
      path: '/kardex'
      fullPath: '/admin/kardex'
      preLoaderRoute: typeof AuthenticatedAdminKardexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagos': {
      id: '/_authenticated/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AuthenticatedAdminPagosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pos': {
      id: '/_authenticated/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AuthenticatedAdminPosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reportes': {
      id: '/_authenticated/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AuthenticatedAdminReportesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ventas': {
      id: '/_authenticated/admin/ventas'
      path: '/ventas'
      fullPath: '/admin/ventas'
      preLoaderRoute: typeof AuthenticatedAdminVentasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/product-image/$': {
      id: '/api/public/product-image/$'
      path: '/api/public/product-image/$'
      fullPath: '/api/public/product-image/$'
      preLoaderRoute: typeof ApiPublicProductImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCajaRoute: typeof AuthenticatedAdminCajaRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminConfiguracionRoute: typeof AuthenticatedAdminConfiguracionRoute
  AuthenticatedAdminInventarioRoute: typeof AuthenticatedAdminInventarioRoute
  AuthenticatedAdminKardexRoute: typeof AuthenticatedAdminKardexRoute
  AuthenticatedAdminPagosRoute: typeof AuthenticatedAdminPagosRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminPosRoute: typeof AuthenticatedAdminPosRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminReportesRoute: typeof AuthenticatedAdminReportesRoute
  AuthenticatedAdminVentasRoute: typeof AuthenticatedAdminVentasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCajaRoute: AuthenticatedAdminCajaRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminConfiguracionRoute: AuthenticatedAdminConfiguracionRoute,
  AuthenticatedAdminInventarioRoute: AuthenticatedAdminInventarioRoute,
  AuthenticatedAdminKardexRoute: AuthenticatedAdminKardexRoute,
  AuthenticatedAdminPagosRoute: AuthenticatedAdminPagosRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminPosRoute: AuthenticatedAdminPosRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminReportesRoute: AuthenticatedAdminReportesRoute,
  AuthenticatedAdminVentasRoute: AuthenticatedAdminVentasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CatalogoRoute: CatalogoRoute,
  CategoriasRoute: CategoriasRoute,
  CheckoutRoute: CheckoutRoute,
  MayorRoute: MayorRoute,
  PedidoRoute: PedidoRoute,
  TestDiagnosticoRoute: TestDiagnosticoRoute,
  ProductoSlugRoute: ProductoSlugRoute,
  ApiPublicProductImageSplatRoute: ApiPublicProductImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
