CREATE TABLE public.prospects (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  phone text NOT NULL,
  state text,
  notes text,
  registered_at date NOT NULL DEFAULT (now() AT TIME ZONE 'America/Caracas')::date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX prospects_phone_unique ON public.prospects (phone);
CREATE INDEX prospects_state_idx ON public.prospects (state);
CREATE INDEX prospects_registered_at_idx ON public.prospects (registered_at DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.prospects TO authenticated;
GRANT ALL ON public.prospects TO service_role;

ALTER TABLE public.prospects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "prospects staff all" ON public.prospects FOR ALL TO authenticated
USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));

CREATE TRIGGER prospects_touch BEFORE UPDATE ON public.prospects
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();